org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.experimental.flutter.embedding=true
android.experimental.flutter.new-embedding=true
android.experimental.flutter.ffi=true
android.experimental.flutter.impeller=true
